apiVersion: kubelet.config.k8s.io/v1
kind: KubeletConfiguration
evictionHard:
  memory.available: "1Gi"
  nodefs.available: "1Gi"
  imagefs.available: "50Gi"
evictionMinimumReclaim:
  memory.available: "0Mi"
  nodefs.available: "500Mi"
  imagefs.available: "2Gi"
